[package]
name = "adventofcode-macro"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
adventofcode-core = { version = "0.1.0", path = "../adventofcode-core" }
proc-macro-error = "1.0.4"
proc-macro2 = "1.0.92"
