[package]
name = "adventofcode-core"
version = "0.1.0"
edition = "2024"

[dependencies]
proc-macro-error = "1.0.4"
proc-macro2 = "1.0.92"
quote = "1.0.38"
syn = { version = "2.0.93", features = ["full"] }
